<?php

namespace Drupal\dp_docs\Entity;

use Drupal\Core\Entity\EntityChangedTrait;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\RevisionableContentEntityBase;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\dp_docs\Traits\AllowEmptyValueTrait;
use Drupal\dp_docs\Traits\APIRefRefTrait;
use Drupal\dp_docs\Traits\AutoLabelTrait;
use Drupal\dp_docs\Traits\MethodParameterTrait;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\dp_docs\APIFormDataParamInterface;
use Drupal\dp_docs\Traits\ItemTrait;
use Drupal\dp_docs\Traits\APIVersionTagRefTrait;
use Drupal\dp_docs\Traits\URLRouteParametersTrait;

/**
 * Defines the API Form Data Param entity class.
 *
 * @ContentEntityType(
 *   id = "api_form_data_param",
 *   label = @Translation("API HTTP Method Form Data Parameter"),
 *   handlers = {
 *     "storage" = "Drupal\dp_docs\APIFormDataParamStorage",
 *     "list_builder" = "Drupal\dp_docs\APIFormDataParamListBuilder",
 *     "view_builder" = "Drupal\dp_docs\DPDocsContentEntityViewBuilder",
 *     "views_data" = "Drupal\dp_docs\APIFormDataParamViewsData",
 *     "form" = {
 *       "default" = "Drupal\dp_docs\Form\DPDocsContentEntityForm",
 *       "add" = "Drupal\dp_docs\Form\DPDocsContentEntityForm",
 *       "edit" = "Drupal\dp_docs\Form\DPDocsContentEntityForm",
 *       "delete" = "Drupal\dp_docs\Form\DPDocsContentEntityDeleteForm",
 *     },
 *     "inline_form" = "Drupal\dp_docs\Form\DPDocsInlineForm",
 *     "route_provider" = {
 *       "html" = "Drupal\dp_docs\APIFormDataParamHtmlRouteProvider",
 *     },
 *     "access" = "Drupal\dp_docs\APIFormDataParamAccessControlHandler",
 *     "translation" = "Drupal\dp_docs\APIFormDataParamTranslationHandler",
 *   },
 *   admin_permission = "administer api form data params",
 *   fieldable = TRUE,
 *   base_table = "api_form_data_param",
 *   data_table = "api_form_data_param_field_data",
 *   field_ui_base_route = "entity.api_form_data_param_type.edit_form",
 *   entity_keys = {
 *     "id" = "id",
 *     "bundle" = "type",
 *     "uuid" = "uuid",
 *     "revision" = "vid",
 *     "langcode" = "langcode",
 *     "label" = "auto_label",
 *   },
 *   api_extra_info = {
 *     "auto_label" = {
 *       "auto_label" = "auto_label",
 *       "autogenerated_label" = "autogenerated_label",
 *     },
 *     "auto_label_source" = "name",
 *     "method_parameter" = {
 *       "name" = "name",
 *       "description" = "description",
 *       "required" = "required",
 *     },
 *     "item" = {
 *       "type" = "param_type",
 *       "format" = "format",
 *       "items" = "api_param_item",
 *       "collection_format" = "collection_format",
 *       "default" = "param_default",
 *     },
 *     "allow_empty_value" = "allow_empty_value",
 *     "api_ref" = "api_ref",
 *     "api_version_tag" = "api_version_tag",
 *   },
 *   bundle_entity_type = "api_form_data_param_type",
 *   bundle_label = @Translation("API HTTP Method Form Data Parameter type"),
 *   revision_table = "api_form_data_param_revision",
 *   revision_data_table = "api_form_data_param_field_revision",
 *   show_revision_ui = TRUE,
 *   revision_metadata_keys = {
 *     "revision_user" = "revision_user",
 *     "revision_created" = "revision_created",
 *     "revision_log_message" = "revision_log",
 *   },
 *   links = {
 *     "canonical" = "/api_form_data_param/{api_form_data_param}",
 *     "add-page" = "/api_form_data_param/add",
 *     "add-form" = "/api_form_data_param/add/{api_form_data_param_type}",
 *     "edit-form" = "/api_form_data_param/{api_form_data_param}/edit",
 *     "delete-form" = "/api_form_data_param/{api_form_data_param}/delete",
 *     "collection" = "/admin/content/api_form_data_param",
 *     "version-history" = "/api_form_data_param/{api_form_data_param}/revisions",
 *     "revision" = "/api_form_data_param/{api_form_data_param}/revisions/{api_form_data_param_revision}/view",
 *     "revision_revert" = "/api_form_data_param/{api_form_data_param}/revisions/{api_form_data_param_revision}/revert",
 *     "revision_delete" = "/api_form_data_param/{api_form_data_param}/revisions/{api_form_data_param_revision}/delete",
 *     "multiple_delete_confirm" = "/admin/content/api_form_data_param/delete",
 *     "translation_revert" = "/api_form_data_param/{api_form_data_param}/revisions/{api_form_data_param_revision}/revert/{langcode}",
 *   },
 *   translatable = TRUE,
 * )
 */
class APIFormDataParam extends RevisionableContentEntityBase implements APIFormDataParamInterface {

  use EntityChangedTrait;
  use AutoLabelTrait;
  use MethodParameterTrait;
  use ItemTrait;
  use AllowEmptyValueTrait;
  use APIRefRefTrait;
  use APIVersionTagRefTrait;
  use URLRouteParametersTrait;

  /**
   * {@inheritdoc}
   */
  public function preSave(EntityStorageInterface $storage) {
    parent::preSave($storage);

    // Generate auto label.
    $this->autoLabelPreSave();
  }

  /**
   * {@inheritdoc}
   */
  public function preSaveRevision(EntityStorageInterface $storage, \stdClass $record) {
    parent::preSaveRevision($storage, $record);

    if (!$this->isNewRevision() && isset($this->original) && (!isset($record->revision_log) || $record->revision_log === '')) {
      // If we are updating an existing APIFormDataParam without adding a new
      // revision, we need to make sure $entity->revision_log is reset whenever
      // it is empty. Therefore, this code allows us to avoid clobbering an
      // existing log entry with an empty one.
      $record->revision_log = $this->original->revision_log->value;
    }
  }

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {
    /** @var \Drupal\Core\Field\BaseFieldDefinition[] $fields */
    $fields = parent::baseFieldDefinitions($entity_type);

    // Add the auto label field.
    $fields += static::autoLabelBaseFieldDefinitions($entity_type);

    // Add the method parameter fields.
    $fields += static::methodParameterBaseFieldDefinitions($entity_type);

    // Add the item fields.
    $fields += static::itemBaseFieldDefinitions($entity_type, TRUE);
    $fields['api_param_item']->setDescription(t('API Parameter Item referenced from API Form Data Parameter.'));

    // Add the allow empty value field.
    $fields += static::allowEmptyValueBaseFieldDefinitions($entity_type);

    // Add the API Reference field.
    $fields += static::apiRefBaseFieldDefinitions($entity_type);
    $fields['api_ref']->setDescription(t('API Reference referenced from API Form Data Parameter.'));

    // Add the API Version Tag field.
    $fields += static::apiVersionTagBaseFieldDefinitions($entity_type);
    $fields['api_version_tag']->setDescription(t('API Version Tag referenced from API Form Data Parameter.'));

    $fields['id']->setDescription(t('The API HTTP Method Form Data Parameter ID.'));

    $fields['uuid']->setDescription(t('The API HTTP Method Form Data Parameter UUID.'));

    $fields['vid']->setDescription(t('The API HTTP Method Form Data Parameter revision ID.'));

    $fields['langcode']->setDescription(t('The API HTTP Method Form Data Parameter language code.'));

    $fields['changed'] = BaseFieldDefinition::create('changed')
      ->setLabel(t('Changed'))
      ->setDescription(t('The time that the API HTTP Method Form Data Parameter was last edited.'))
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE);

    return $fields;
  }

  /**
   * {@inheritdoc}
   */
  public function label() {
    $label = parent::label();
    if (empty($label)) {
      $label = $this->generateAutoLabel();
    }
    return $label;
  }

}
