<?php

namespace Drupal\dp_docs\Entity;

use Drupal\Core\Entity\EntityChangedTrait;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\RevisionableContentEntityBase;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\dp_docs\Traits\APIDocRefTrait;
use Drupal\dp_docs\Traits\APIRefRefTrait;
use Drupal\dp_docs\Traits\AutoLabelTrait;
use Drupal\dp_docs\APITagInterface;
use Drupal\dp_docs\Traits\APIExtDocRefTrait;
use Drupal\dp_docs\Traits\URLRouteParametersTrait;
use Drupal\dp_docs\Traits\VendorExtensionTrait;
use Drupal\dp_docs\Traits\APIVersionTagRefTrait;

/**
 * Defines the API Tag entity class.
 *
 * @ContentEntityType(
 *   id = "api_tag",
 *   label = @Translation("API Tag"),
 *   handlers = {
 *     "storage" = "Drupal\dp_docs\APITagStorage",
 *     "list_builder" = "Drupal\dp_docs\APITagListBuilder",
 *     "view_builder" = "Drupal\dp_docs\DPDocsContentEntityViewBuilder",
 *     "views_data" = "Drupal\dp_docs\APITagViewsData",
 *     "form" = {
 *       "default" = "Drupal\dp_docs\Form\DPDocsContentEntityForm",
 *       "add" = "Drupal\dp_docs\Form\DPDocsContentEntityForm",
 *       "edit" = "Drupal\dp_docs\Form\DPDocsContentEntityForm",
 *       "delete" = "Drupal\dp_docs\Form\DPDocsContentEntityDeleteForm",
 *     },
 *     "inline_form" = "Drupal\dp_docs\Form\DPDocsInlineForm",
 *     "route_provider" = {
 *       "html" = "Drupal\dp_docs\APITagHtmlRouteProvider",
 *     },
 *     "access" = "Drupal\dp_docs\APITagAccessControlHandler",
 *     "translation" = "Drupal\dp_docs\APITagTranslationHandler",
 *   },
 *   admin_permission = "administer api tags",
 *   fieldable = TRUE,
 *   base_table = "api_tag",
 *   data_table = "api_tag_field_data",
 *   field_ui_base_route = "entity.api_tag_type.edit_form",
 *   entity_keys = {
 *     "id" = "id",
 *     "bundle" = "type",
 *     "uuid" = "uuid",
 *     "revision" = "vid",
 *     "langcode" = "langcode",
 *     "label" = "auto_label",
 *   },
 *   api_extra_info = {
 *     "auto_label" = {
 *       "auto_label" = "auto_label",
 *       "autogenerated_label" = "autogenerated_label",
 *     },
 *     "auto_label_source" = "name",
 *     "vendor_extension" = "extensions",
 *     "api_ext_doc" = "api_ext_doc",
 *     "api_doc" = "api_doc",
 *     "api_ref" = "api_ref",
 *     "api_version_tag" = "api_version_tag",
 *   },
 *   bundle_entity_type = "api_tag_type",
 *   bundle_label = @Translation("API Tag type"),
 *   revision_table = "api_tag_revision",
 *   revision_data_table = "api_tag_field_revision",
 *   show_revision_ui = TRUE,
 *   revision_metadata_keys = {
 *     "revision_created" = "revision_created",
 *     "revision_user" = "revision_user",
 *     "revision_log_message" = "revision_log",
 *   },
 *   links = {
 *     "canonical" = "/api_tag/{api_tag}",
 *     "add-page" = "/api_tag/add",
 *     "add-form" = "/api_tag/add/{api_tag_type}",
 *     "edit-form" = "/api_tag/{api_tag}/edit",
 *     "delete-form" = "/api_tag/{api_tag}/delete",
 *     "collection" = "/admin/content/api_tag",
 *     "version-history" = "/api_tag/{api_tag}/revisions",
 *     "revision" = "/api_tag/{api_tag}/revisions/{api_tag_revision}/view",
 *     "revision_revert" = "/api_tag/{api_tag}/revisions/{api_tag_revision}/revert",
 *     "revision_delete" = "/api_tag/{api_tag}/revisions/{api_tag_revision}/delete",
 *     "multiple_delete_confirm" = "/admin/content/api_tag/delete",
 *     "translation_revert" = "/api_tag/{api_tag}/revisions/{api_tag_revision}/revert/{langcode}",
 *   },
 *   translatable = TRUE,
 * )
 */
class APITag extends RevisionableContentEntityBase implements APITagInterface {

  use EntityChangedTrait;
  use VendorExtensionTrait;
  use AutoLabelTrait;
  use APIExtDocRefTrait;
  use APIDocRefTrait;
  use APIRefRefTrait;
  use APIVersionTagRefTrait;
  use URLRouteParametersTrait;

  /**
   * {@inheritdoc}
   */
  public function getName() {
    return $this->get('name')->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setName($name) {
    $this->set('name', $name);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->get('description')->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setDescription($description) {
    $this->set('description', $description);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function preSave(EntityStorageInterface $storage) {
    parent::preSave($storage);

    // Generate auto label.
    $this->autoLabelPreSave();
  }

  /**
   * {@inheritdoc}
   */
  public function preSaveRevision(EntityStorageInterface $storage, \stdClass $record) {
    parent::preSaveRevision($storage, $record);

    if (!$this->isNewRevision() && isset($this->original) && (!isset($record->revision_log) || $record->revision_log === '')) {
      // If we are updating an existing APITag without adding a new
      // revision, we need to make sure $entity->revision_log is reset whenever
      // it is empty. Therefore, this code allows us to avoid clobbering an
      // existing log entry with an empty one.
      $record->revision_log = $this->original->revision_log->value;
    }
  }

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {
    /** @var \Drupal\Core\Field\BaseFieldDefinition[] $fields */
    $fields = parent::baseFieldDefinitions($entity_type);

    // Add the auto label field.
    $fields += static::autoLabelBaseFieldDefinitions($entity_type);

    // Add the vendor extension fields.
    $fields += static::vendorExtensionBaseFieldDefinitions($entity_type);

    // Add the API External Documentation field.
    $fields += static::apiExtDocBaseFieldDefinitions($entity_type);
    $fields['api_ext_doc']->setDescription(t('API External Documentation referenced from API Tag.'));

    // Add the API Documentation field.
    $fields += static::apiDocBaseFieldDefinitions($entity_type);
    $fields['api_doc']->setDescription(t('API Documentation referenced from API Tag.'));

    // Add the API Reference field.
    $fields += static::apiRefBaseFieldDefinitions($entity_type);
    $fields['api_ref']->setDescription(t('API Reference referenced from API Tag.'));

    // Add the API Version Tag field.
    $fields += static::apiVersionTagBaseFieldDefinitions($entity_type);
    $fields['api_version_tag']->setDescription(t('API Version Tag referenced from API Tag.'));

    $fields['id']->setDescription(t('The API Tag ID.'));

    $fields['uuid']->setDescription(t('The API Tag UUID.'));

    $fields['vid']->setDescription(t('The API Tag revision ID.'));

    $fields['langcode']->setDescription(t('The API Tag language code.'));

    $fields['name'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Name'))
      ->setRequired(TRUE)
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE)
      ->setSetting('max_length', 255)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'string',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['description'] = BaseFieldDefinition::create('text_long')
      ->setLabel(t('Description'))
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'text_default',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'text_textfield',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['changed'] = BaseFieldDefinition::create('changed')
      ->setLabel(t('Changed'))
      ->setDescription(t('The time that the API Tag was last edited.'))
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE);

    return $fields;
  }

  /**
   * {@inheritdoc}
   */
  public function label() {
    $label = parent::label();
    if (empty($label)) {
      $label = $this->generateAutoLabel();
    }
    return $label;
  }

}
